shield_pre_level = 10
battery_value = 50
small_battery_value = 10
sheild_cooldown = 0
mobs_shield = true
mobs_shield_add_percent = 0.5
send_charging_msg = false
messages = ["", ""]
messages_phoenix = [""]

[display]
	shield = false
	health = false
	number = true
	hud = true

[misc]
	use_2d_head = true
	use_glass_break_sound = false

[func]
	#Set damage to 0 when protected by shield.It will cause some mod cannot recognize this damage.
	zero_damage_event = false
	#Calculate damage on shield with event. All damage on shield will be calculated with our mixin function in LivingEntity.hurt after any other hooks. If enabled, we will use forge event with lowest priority instead.
	calc_damage_with_event = false

